### ISSUE TITLE
Update to 2.1.0 broke site, had to disable/remove plugin

### ISSUE THREAD

**Issue by bossanova808** [jalendport/craft-preparse#100]
The move from besteadfast to jalendport is not going so well for me...Things appeared ok when I updated, and the migration ran successfully.

However, subsequently, am seeing errors loading all site pages.

Even a manual `composer remove` of the old, and `require` of the new, does not fix it, nor the more thorough:
`rm -rf vendor/ && rm composer.lock && composer clear-cache && composer update`

If the plugin is installed and enabled, the entire site fails to load with this:

```
yii\base\UnknownPropertyException: Getting unknown property: jalendport\preparse\PreparseField::preparseFieldService in /var/www/html/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('preparseFieldSe...')
#1 /var/www/html/vendor/jalendport/craft-preparse/src/PreparseField.php(90): yii\di\ServiceLocator->__get('preparseFieldSe...')
#2 [internal function]: jalendport\preparse\PreparseField->jalendport\preparse\{closure}(Object(craft\events\ElementEvent))
#3 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#4 /var/www/html/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('craft\\services\\...', 'beforeSaveEleme...', Object(craft\events\ElementEvent))
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(3212): yii\base\Component->trigger('beforeSaveEleme...', Object(craft\events\ElementEvent))
#6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1108): craft\services\Elements->_saveElementInternal(Object(craft\commerce\elements\Order), true, false, NULL, NULL, false, false)
#7 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\services\Elements->saveElement(Object(craft\commerce\elements\Order))
#8 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(148): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'saveElement', Array, 'method', false, false, false, 23)
#9 /var/www/html/storage/runtime/compiled_templates/00/00ff691621c2fbe5dda507bbbc7a31ba.php(86): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\Elements), 'saveElement', Array, 'method', false, false, false, 23)
#10 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_c592fb17a467c210c0e267958aff0e6a->block_structure(Array, Array)
#11 /var/www/html/storage/runtime/compiled_templates/3c/3cb3549fcdd50266deca6b418db48ad6.php(273): Twig\Template->displayBlock('structure', Array, Array)
#12 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_39c0d2a0f0d5912e5425a4fd62f180d7->doDisplay(Array, Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/www/html/storage/runtime/compiled_templates/00/00ff691621c2fbe5dda507bbbc7a31ba.php(46): Twig\Template->display(Array, Array)
#15 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c592fb17a467c210c0e267958aff0e6a->doDisplay(Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#18 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#19 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/View.php(488): Twig\Environment->render('cart/shipping', Array)
#21 /var/www/html/vendor/craftcms/cms/src/web/View.php(541): craft\web\View->renderTemplate('cart/shipping', Array)
#22 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('cart/shipping', Array, 'site')
#23 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#24 /var/www/html/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#25 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#26 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#27 /var/www/html/web/index.php(12): yii\base\Application->run()
#28 {main}
```

**Comment by jalendport** [comment]
I was overhasty in removing what I thought was some obsolete code as I was going through and renaming things; added the (evidently) necessary code back in v2.1.1. Sorry for the inconvenience! 😬
